name: Khaldiya
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  carousel_pro: ^1.0.0
  provider: ^4.3.2+2
  url_launcher: ^5.7.8
  share: ^0.6.5+3
  flutter_launcher_icons: ^0.8.1
  http: ^0.12.2
  cached_network_image: ^2.4.1
  get_mac: ^0.0.1
  shared_preferences: ^0.5.12+4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "asset/Image/logoapp.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - asset/Image/logocart.png
     - asset/Image/logofile.png
     - asset/Image/logooffer.png
     - asset/Image/logosupostr.png
     - asset/Image/loguot.png
     - asset/Image/shaer.png
     - asset/Image/cash.png
     - asset/Image/keymet.png
     - asset/Image/facebook.png
     - asset/Image/instagram.png
     - asset/Image/snapchat.png
     - asset/Image/twitter.png
     - asset/Image/imagedg.jpg
     - asset/Image/offerday.jpg
     - asset/Image/cart_empty.png
     - asset/Image/delete.png
     - asset/Image/bgCat.jpg
     - asset/Image/baner1.jpg
     - asset/Image/baner2.jpg
     - asset/Image/baner3.jpg
     - asset/Image/tenor.gif

  # example:
  fonts:
     - family: Almarai
       fonts:
         - asset: asset/Font/Almarai-Regular.ttf


     - family: BebasNeue
       fonts:
         - asset: asset/Font/BebasNeue-Regular.ttf



#
#     - family: JFFlat
#       fonts:
#         - asset: asset/Font/JF-Flat-regular.otf
#

